name: Feature Branch

on:
  workflow_dispatch:
  push:
    branches:
      - feature/commit
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
    types: [closed]

# Jobs
jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    # - name: shell
    #   run: |
    #     echo "${{toJSON(github.event)}}"

    - name: my actions
      uses: harsh896/rocketChat-notification-github-actions@feature/commit
      if: always()
      with:
        type: ${{ job.status }}
        id: ${{ github.run_number }}
        job_name: '*${{ github.workflow }}* Github Action'
        userNameWhoTriggeredTheWorkflow: "${{ github.actor }}"
        mention: 'here'
        mention_if: 'failure'
        channel: '#github-actions'
        url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
        message: Teting Message  
        commit: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}
        
