name: Rocket chat notification

on:
  workflow_dispatch:
  push:
    branches:
      - master

# Jobs
jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: my actions
      uses: ./
      with:
        host: harsh