name: Rocket chat notification

on:
  workflow_dispatch:
  push:
    branches:
      - master

# Jobs
jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: my actions
      uses: harsh896/rocketChat-notification-github-actions@v1.0
      if: always()
      with:
        type: ${{ job.status }}
        id: ${{ github.run_number }}
        job_name: '*${{ github.workflow }}* Github Action'
        userNameWhoTriggeredTheWorkflow: "${{ github.actor }}"
        mention: 'here'
        mention_if: 'failure'
        channel: '#github-actions'
        url: ${{ secrets.ROCKETCHAT_WEBHOOK }}  
        commit: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}
        
