name: Rocket chat notification

on:
  workflow_dispatch:
  push:
    branches:
      - master

# Jobs
jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: my actions
      uses: ./
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*${{ github.workflow }}* Github Action -> '
        #icon_emoji: ${{ env.EMOJI }}
        mention: 'all'
        mention_if: 'failure'
        channel: '#github-actions'
        url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
        #message: 'testing message field'  
        commit: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}
